/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz_program;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author EXCALIBUR
 */
public class Quiz extends javax.swing.JFrame {
    int counter = 1;
    Color oldColor = new Color(0, 0, 102);
    int result;
    /**
     * Creates new form Quiz
     */
    public Quiz() {
        initComponents();
        QuestionArea.setText("Which of the following countries did not participate in the WW2?");
        AnswerA.setForeground(Color.WHITE);
        AnswerB.setForeground(Color.WHITE);
        AnswerC.setForeground(Color.WHITE);
        AnswerD.setForeground(Color.WHITE);
        BtnNext.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        QuestionArea = new javax.swing.JTextArea();
        QuestionNumber = new javax.swing.JLabel();
        Label1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        Label4 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        Label5 = new javax.swing.JLabel();
        Label6 = new javax.swing.JLabel();
        Label7 = new javax.swing.JLabel();
        Label8 = new javax.swing.JLabel();
        Label9 = new javax.swing.JLabel();
        Label11 = new javax.swing.JLabel();
        Label10 = new javax.swing.JLabel();
        Label12 = new javax.swing.JLabel();
        AnswerA = new javax.swing.JButton();
        AnswerB = new javax.swing.JButton();
        AnswerC = new javax.swing.JButton();
        AnswerD = new javax.swing.JButton();
        BtnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(600, 350, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        QuestionArea.setBackground(new java.awt.Color(255, 255, 255));
        QuestionArea.setColumns(20);
        QuestionArea.setRows(5);
        jScrollPane1.setViewportView(QuestionArea);

        QuestionNumber.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        QuestionNumber.setForeground(new java.awt.Color(0, 0, 0));
        QuestionNumber.setText("Question 1");

        Label1.setBackground(new java.awt.Color(255, 255, 255));
        Label1.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        Label1.setForeground(new java.awt.Color(255, 255, 255));
        Label1.setText("1- 1000");

        Label2.setBackground(new java.awt.Color(255, 255, 255));
        Label2.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        Label2.setForeground(new java.awt.Color(255, 255, 255));
        Label2.setText("2- 5000");

        Label4.setBackground(new java.awt.Color(255, 255, 255));
        Label4.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        Label4.setForeground(new java.awt.Color(255, 255, 255));
        Label4.setText("4- 15000");

        Label3.setBackground(new java.awt.Color(255, 255, 255));
        Label3.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        Label3.setForeground(new java.awt.Color(255, 255, 255));
        Label3.setText("3- 10000");

        Label5.setBackground(new java.awt.Color(255, 255, 255));
        Label5.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        Label5.setForeground(new java.awt.Color(255, 255, 255));
        Label5.setText("5- 20000");

        Label6.setBackground(new java.awt.Color(255, 255, 255));
        Label6.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        Label6.setForeground(new java.awt.Color(255, 255, 255));
        Label6.setText("6- 25000");

        Label7.setBackground(new java.awt.Color(255, 255, 255));
        Label7.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        Label7.setForeground(new java.awt.Color(255, 255, 255));
        Label7.setText("7- 50000");

        Label8.setBackground(new java.awt.Color(255, 255, 255));
        Label8.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        Label8.setForeground(new java.awt.Color(255, 255, 255));
        Label8.setText("8- 100000");

        Label9.setBackground(new java.awt.Color(255, 255, 255));
        Label9.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        Label9.setForeground(new java.awt.Color(255, 255, 255));
        Label9.setText("9- 250000");

        Label11.setBackground(new java.awt.Color(255, 255, 255));
        Label11.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        Label11.setForeground(new java.awt.Color(255, 255, 255));
        Label11.setText("11- 750000");

        Label10.setBackground(new java.awt.Color(255, 255, 255));
        Label10.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        Label10.setForeground(new java.awt.Color(255, 255, 255));
        Label10.setText("10- 500000");

        Label12.setBackground(new java.awt.Color(255, 255, 255));
        Label12.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        Label12.setForeground(new java.awt.Color(255, 255, 255));
        Label12.setText("12- 1000000");

        AnswerA.setBackground(new java.awt.Color(0, 0, 102));
        AnswerA.setText("A-) Japan");
        AnswerA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AnswerA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerAActionPerformed(evt);
            }
        });

        AnswerB.setBackground(new java.awt.Color(0, 0, 102));
        AnswerB.setText("B-) China");
        AnswerB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AnswerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerBActionPerformed(evt);
            }
        });

        AnswerC.setBackground(new java.awt.Color(0, 0, 102));
        AnswerC.setText("C-) Sweden");
        AnswerC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AnswerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerCActionPerformed(evt);
            }
        });

        AnswerD.setBackground(new java.awt.Color(0, 0, 102));
        AnswerD.setText("D-) Thailand");
        AnswerD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AnswerD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerDActionPerformed(evt);
            }
        });

        BtnNext.setBackground(new java.awt.Color(0, 0, 102));
        BtnNext.setText("Next >>");
        BtnNext.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(QuestionNumber)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AnswerA, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AnswerC, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AnswerD, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AnswerB, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label12)
                    .addComponent(Label5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label7)
                    .addComponent(Label8)
                    .addComponent(Label9)
                    .addComponent(Label11)
                    .addComponent(Label10))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label10)
                        .addGap(1, 1, 1)
                        .addComponent(Label9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label8)
                        .addGap(2, 2, 2)
                        .addComponent(Label7)
                        .addGap(3, 3, 3)
                        .addComponent(Label6)
                        .addGap(2, 2, 2)
                        .addComponent(Label5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(QuestionNumber)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AnswerA)
                            .addComponent(AnswerB))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AnswerC)
                            .addComponent(AnswerD))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnNext)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void AnswerDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerDActionPerformed
        if(counter == 1){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerD.setBackground(Color.red);
                AnswerC.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 0 TL");
            }
        }
        if(counter == 2){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerD.setBackground(Color.red);
            AnswerB.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 1000 TL");
            } 
        }
        if(counter == 3){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerD.setBackground(Color.green);
            Label3.setForeground(Color.orange);
            BtnNext.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "Well done math genious. Move on!");
            } 
        }
        if(counter == 4){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerD.setBackground(Color.red);
            AnswerA.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 10000 TL");
            } 
        }
        if(counter == 5){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerD.setBackground(Color.red);
            AnswerB.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 15000 TL");
            } 
        }
        if(counter == 6){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerD.setBackground(Color.red);
            AnswerA.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 20000 TL");
            } 
        }
        if(counter == 7){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerD.setBackground(Color.red);
                AnswerC.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 25000 TL");
            }
        }
        if(counter == 8){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerD.setBackground(Color.green);
                Label8.setForeground(Color.orange);
                BtnNext.setEnabled(true);
                JOptionPane.showMessageDialog(rootPane, "Ja, es ist richtig. Los los!");
            }
        }
        if(counter == 9){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerD.setBackground(Color.green);
                Label9.setForeground(Color.orange);
                BtnNext.setEnabled(true);
                JOptionPane.showMessageDialog(rootPane, "You are going perfect! Ready for next one?");
            }
        }
        if(counter == 10){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerD.setBackground(Color.red);
                AnswerA.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 250000 TL");
            }
        }
        if(counter == 11){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerD.setBackground(Color.red);
                AnswerB.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 500000 TL");
            }
        }
        if(counter == 12){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerD.setBackground(Color.red);
                AnswerA.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 750000 TL");
            }
        }
    }//GEN-LAST:event_AnswerDActionPerformed

    private void AnswerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerCActionPerformed
        if(counter == 1){
            result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerC.setBackground(Color.green);
                Label1.setForeground(Color.orange);
                BtnNext.setEnabled(true);
                JOptionPane.showMessageDialog(rootPane, "Good Job! Move on the next question");
            }
        }
        if(counter == 2){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerC.setBackground(Color.red);
            AnswerB.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 1000 TL");
            } 
        }
        if(counter == 3){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerC.setBackground(Color.red);
            AnswerD.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 5000 TL");
            } 
        }
        if(counter == 4){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerC.setBackground(Color.red);
            AnswerA.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 10000 TL");
            } 
        }
        if(counter == 5){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerC.setBackground(Color.red);
            AnswerB.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 15000 TL");
            } 
        }
        if(counter == 6){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerC.setBackground(Color.red);
            AnswerA.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 20000 TL");
            } 
        }
        if(counter == 7){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerC.setBackground(Color.green);
                Label7.setForeground(Color.orange);
                BtnNext.setEnabled(true);
                JOptionPane.showMessageDialog(rootPane, "Nice one. Go to the next question");
            }
        }
        if(counter == 8){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerC.setBackground(Color.red);
                AnswerD.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 50000 TL");
            }
        }
        if(counter == 9){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerC.setBackground(Color.red);
                AnswerD.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 100000 TL");
            }
        }
        if(counter == 10){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerC.setBackground(Color.red);
                AnswerA.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 250000 TL");
            }
        }
        if(counter == 11){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerC.setBackground(Color.red);
                AnswerB.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 500000 TL");
            }
        }
        if(counter == 12){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerC.setBackground(Color.red);
                AnswerA.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 750000 TL");
            }
        }
    }//GEN-LAST:event_AnswerCActionPerformed

    private void AnswerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerBActionPerformed
        if(counter == 1){
            result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerB.setBackground(Color.red);
                AnswerC.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 0 TL");
            }
        }
        if(counter == 2){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerB.setBackground(Color.green);
            Label2.setForeground(Color.orange);
            BtnNext.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "Bravo! Move on the next question");
            } 
        }
        if(counter == 3){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerB.setBackground(Color.red);
            AnswerD.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 5000 TL");
            } 
        }
        if(counter == 4){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerB.setBackground(Color.red);
            AnswerA.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 10000 TL");
            } 
        }
        if(counter == 5){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerB.setBackground(Color.green);
            Label5.setForeground(Color.orange);
            BtnNext.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "Very good. Go to the next one!");
            } 
        }
        if(counter == 6){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerB.setBackground(Color.red);
            AnswerA.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 20000 TL");
            } 
        }
        if(counter == 7){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerB.setBackground(Color.red);
                AnswerC.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 25000 TL");
            }
        }
        if(counter == 8){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerB.setBackground(Color.red);
                AnswerD.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 50000 TL");
            }
        }
        if(counter == 9){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerB.setBackground(Color.red);
                AnswerD.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 100000 TL");
            }
        }
        if(counter == 10){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerB.setBackground(Color.red);
                AnswerA.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 250000 TL");
            }
        }
        if(counter == 11){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerB.setBackground(Color.green);
                Label11.setForeground(Color.orange);
                BtnNext.setEnabled(true);
                JOptionPane.showMessageDialog(rootPane, "Perfect. You have only one question to be a millionaire!");
            }
        }
        if(counter == 12){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerB.setBackground(Color.red);
                AnswerA.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 750000 TL");
            }
        }
    }//GEN-LAST:event_AnswerBActionPerformed

    private void AnswerAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerAActionPerformed
        if(counter == 1){
            result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerA.setBackground(Color.red);
                AnswerC.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 0 TL");
            }
        }
        if(counter == 2){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerA.setBackground(Color.red);
            AnswerB.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 1000 TL");
            } 
        }
        if(counter == 3){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerA.setBackground(Color.red);
            AnswerD.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 5000 TL");
            } 
        }
        if(counter == 4){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerA.setBackground(Color.green);
            Label4.setForeground(Color.orange);
            BtnNext.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "Impressive. Let's keep up!");
            } 
        }
        if(counter == 5){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerA.setBackground(Color.red);
            AnswerB.setBackground(Color.yellow);
            JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 15000 TL");
            } 
        }
        if(counter == 6){
           result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(result == JOptionPane.YES_OPTION){
            AnswerA.setBackground(Color.green);
            Label6.setForeground(Color.orange);
            BtnNext.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "Halfway there. Keep it up!");
            } 
        }
        if(counter == 7){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerA.setBackground(Color.red);
                AnswerC.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 25000 TL");
            }
        }
        if(counter == 8){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerA.setBackground(Color.red);
                AnswerD.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 50000 TL");
            }
        }
        if(counter == 9){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerA.setBackground(Color.red);
                AnswerD.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 100000 TL");
            }
        }
        if(counter == 10){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerA.setBackground(Color.green);
                Label10.setForeground(Color.orange);
                BtnNext.setEnabled(true);
                JOptionPane.showMessageDialog(rootPane, "Hats off to you! You have only 2 question let's go");
            }
        }
        if(counter == 11){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerA.setBackground(Color.red);
                AnswerB.setBackground(Color.YELLOW);
                JOptionPane.showMessageDialog(rootPane, "You have lost. Money that you got is 500000 TL");
            }
        }
        if(counter == 12){
             result = JOptionPane.showConfirmDialog(this, "Last Decision?", "Confirm", JOptionPane.YES_NO_OPTION);
            if(result == JOptionPane.YES_OPTION){
                AnswerA.setBackground(Color.green);
                Label12.setForeground(Color.orange);
                JOptionPane.showMessageDialog(rootPane, "CONGRATULATIONS!. YOU ANSWERED ALL THE QUESTIONS CORRECTLY AND YOU HAVE JUST WON A MILLION TL!!!");
            }
        }
    }//GEN-LAST:event_AnswerAActionPerformed

    private void BtnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNextActionPerformed
        counter++;
        QuestionNumber.setText("Question " + counter);
        switch(counter){
            case 2:
                QuestionArea.setText("How many moons does Mars have?");
                AnswerA.setText("A-) 1");
                AnswerB.setText("B-) 2");
                AnswerC.setText("C-) 3");
                AnswerC.setBackground(oldColor);
                AnswerD.setText("D-) 4");
                break;
            case 3:
                QuestionArea.setText("Which one of these numbers at the below is a prime number?");
                AnswerA.setText("A-) 511");
                AnswerB.setBackground(oldColor);                           
                AnswerB.setText("B-) 839");
                AnswerC.setText("C-) 777");
                AnswerD.setText("D-) 971");
                break;
            case 4:
                QuestionArea.setText("Who was the first person landed in Antarctica?");
                AnswerA.setText("A-) John Davis");
                AnswerB.setText("B-) James Cook");
                AnswerC.setText("C-) Richard E. Byrd");
                AnswerD.setBackground(oldColor);
                AnswerD.setText("D-) Emilio Marcos Palma");
                break;
            case 5:
                QuestionArea.setText("Which organ can't regenerate itself?");
                AnswerA.setText("A-) Lungs");
                AnswerA.setBackground(oldColor);
                AnswerB.setText("B-) Brain");
                AnswerC.setText("C-) Stomach");
                AnswerD.setText("D-) Bowel");
                break;
            case 6:
                QuestionArea.setText("What is the most radioactive element?");
                AnswerA.setText("A-) Polonium");
                AnswerB.setText("B-) Uranium");
                AnswerB.setBackground(oldColor);
                AnswerC.setText("C-) Radium");
                AnswerD.setText("D-) Plutonium");
                break;
            case 7:
                QuestionArea.setText("Which word has a different meaning?");
                AnswerA.setText("A-) Scrupulous");
                AnswerA.setBackground(oldColor);
                AnswerB.setText("B-) Rigorous");
                AnswerC.setText("C-) Indigenous");
                AnswerD.setText("D-) Fastidious");
                break;
            case 8:
                QuestionArea.setText("How many flags Germany had in history?");
                AnswerA.setText("A-) 6");
                AnswerB.setText("B-) 7");
                AnswerC.setText("C-) 8");
                AnswerC.setBackground(oldColor);
                AnswerD.setText("D-) 9");
                break;
            case 9:
                QuestionArea.setText("How many Olympics Medals Michael Phelps have?");
                AnswerA.setText("A-) 16");
                AnswerB.setText("B-) 22");
                AnswerC.setText("C-) 24");
                AnswerD.setText("D-) 28");
                AnswerD.setBackground(oldColor);
                break;
            case 10:
                QuestionArea.setText("Which volcano is a dormat volcano?");
                AnswerA.setText("A-) Mount Ararat");
                AnswerB.setText("B-) Kanlaon");
                AnswerC.setText("C-) Etna");
                AnswerD.setText("D-) Great Sitkin");
                AnswerD.setBackground(oldColor);
                break;
            case 11:
                QuestionArea.setText("Which dictator has the largest kill count in history");
                AnswerA.setText("A-) Adolf Hitler");
                AnswerA.setBackground(oldColor);
                AnswerB.setText("B-) Mao Zedong");
                AnswerC.setText("C-) Joseph Stalin");
                AnswerD.setText("D-) Emperor Hirohito");
                break;
            case 12:
                QuestionArea.setText("What is the launch date of The Ulysses spacecraft?");
                AnswerA.setText("A-) 6 October 1990");
                AnswerB.setText("B-) 28 September 1991");
                AnswerB.setBackground(oldColor);
                AnswerC.setText("C-) 19 August 1989");
                AnswerD.setText("D-) 22 December 1992");
                break;
        }
        BtnNext.setEnabled(false);
    }//GEN-LAST:event_BtnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnswerA;
    private javax.swing.JButton AnswerB;
    private javax.swing.JButton AnswerC;
    private javax.swing.JButton AnswerD;
    private javax.swing.JButton BtnNext;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label10;
    private javax.swing.JLabel Label11;
    private javax.swing.JLabel Label12;
    private javax.swing.JLabel Label2;
    private javax.swing.JLabel Label3;
    private javax.swing.JLabel Label4;
    private javax.swing.JLabel Label5;
    private javax.swing.JLabel Label6;
    private javax.swing.JLabel Label7;
    private javax.swing.JLabel Label8;
    private javax.swing.JLabel Label9;
    private javax.swing.JTextArea QuestionArea;
    private javax.swing.JLabel QuestionNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
